preseed_create: ajout set options

diff --git a/preseed_create b/preseed_create
--- a/preseed_create
+++ b/preseed_create
@@ -7,6 +7,12 @@
 #  exit 1
 #fi
 
+# e - script stops on error
+# u - error if undefined variable
+# o pipefail - script fails if command piped fails
+# x - output each line (debug)
+set -euo pipefail
+
 export DEBIAN_FRONTEND=noninteractive
 export NEEDRESTART_MODE=a
 
